name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      prerelease:
        description: 'Is this a pre-release?'
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      deployments: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN || github.token }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: |
        npm run type-check
        npm run lint
        npm run build
        
    - name: Configure Git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
    - name: Bump version
      id: version
      run: |
        NEW_VERSION=$(npm version ${{ github.event.inputs.version }} --no-git-tag-version)
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "version_number=${NEW_VERSION#v}" >> $GITHUB_OUTPUT
        
    - name: Update CHANGELOG
      run: |
        echo "# Changelog" > CHANGELOG.temp
        echo "" >> CHANGELOG.temp
        echo "## [${{ steps.version.outputs.version_number }}] - $(date +%Y-%m-%d)" >> CHANGELOG.temp
        echo "" >> CHANGELOG.temp
        echo "### Added" >> CHANGELOG.temp
        echo "- Version ${{ steps.version.outputs.version_number }} release" >> CHANGELOG.temp
        echo "" >> CHANGELOG.temp
        if [ -f CHANGELOG.md ]; then
          tail -n +2 CHANGELOG.md >> CHANGELOG.temp
        fi
        mv CHANGELOG.temp CHANGELOG.md
        
    - name: Commit changes
      run: |
        git add package.json package-lock.json CHANGELOG.md
        git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}"
        git tag ${{ steps.version.outputs.new_version }}
        
    - name: Push changes
      run: |
        git push origin ${{ github.ref_name }}
        git push origin ${{ steps.version.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create GitHub Release
      uses: actions/github-script@v7
      with:
        script: |
          const { data: release } = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: '${{ steps.version.outputs.new_version }}',
            name: 'Release ${{ steps.version.outputs.new_version }}',
            body: `## What's Changed\n\n- Version ${{ steps.version.outputs.version_number }} release\n\n**Full Changelog**: https://github.com/${context.repo.owner}/${context.repo.repo}/compare/v0.0.1...${{ steps.version.outputs.new_version }}`,
            draft: false,
            prerelease: ${{ github.event.inputs.prerelease }}
          });
          
          core.info(`Release created: ${release.html_url}`);
        
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create deployment status
      if: success()
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: |
          try {
            await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              environment: 'npm-registry',
              description: 'Published to NPM registry'
            });
            core.info('Deployment status created successfully!');
          } catch (error) {
            core.warning(`Failed to create deployment status: ${error.message}`);
          }
          
          core.info('Package published to NPM successfully!');